version: "3"
services:
  redis4proxypool:
    image: redis:alpine
    container_name: redis4proxypool
  proxypool:
    build: .
    image: "zhaojiedi/scrapy_proxy_pool:latest"
    container_name: proxypool
    ports:
      - "5555:5555"
    restart: always
    # volumes:
    #   - proxypool/crawlers/private:~/proxypool/crawlers/private
    environment:
      REDIS_HOST: redis4proxypool
